#!/usr/bin/env node
// Builds a self-contained Worker for deployments that cannot use the static-assets upload API
// (REST-only environments that cannot present the per-session upload JWT, for example).
//
//   dist/inline/worker.js  the normal bundle from `wrangler deploy --dry-run --outdir dist`, unchanged
//   dist/inline/index.js   generated entry: re-exports Ledger, serves public/ from memory when the
//                          ASSETS binding is absent, and delegates everything else to worker.js
//
// Upload both files as ES modules (main_module = "index.js") and omit the assets binding. With
// Wrangler you never need this: `wrangler deploy` uploads public/ as real static assets, and the
// generated entry defers to that binding whenever it exists.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const publicDir = join(root, "public");
const distDir = join(root, "dist");
const outDir = join(distDir, "inline");

const CONTENT_TYPES = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".txt": "text/plain; charset=utf-8",
};

/** Deterministic: same files (sorted by path) always produce byte-identical output. */
function renderInlineEntry(files) {
  const entries = files.map((f) => `  ${JSON.stringify(f.path)}: [${JSON.stringify(f.type)}, ${JSON.stringify(f.body)}],`);
  return [
    "// Generated by deploy/build-inline.mjs from public/ - do not edit.",
    "// Serves the dashboard from memory when the Worker has no ASSETS binding (REST-only deploys).",
    'import worker, { Ledger } from "./worker.js";',
    "export { Ledger };",
    "",
    "const FILES = {",
    ...entries,
    "};",
    'FILES["/"] = FILES["/index.html"];',
    "",
    "function serve(request) {",
    '  if (request.method !== "GET" && request.method !== "HEAD") {',
    '    return new Response("Method Not Allowed", { status: 405, headers: { allow: "GET, HEAD" } });',
    "  }",
    "  const file = FILES[new URL(request.url).pathname];",
    '  if (!file) return new Response("Not Found", { status: 404, headers: { "content-type": "text/plain; charset=utf-8" } });',
    '  const headers = { "content-type": file[0], "cache-control": "public, max-age=300" };',
    '  return new Response(request.method === "HEAD" ? null : file[1], { status: 200, headers });',
    "}",
    "",
    "const inlineAssets = { fetch: async (request) => serve(request) };",
    "",
    "export default {",
    "  fetch(request, env, ctx) {",
    "    return worker.fetch(request, env.ASSETS ? env : { ...env, ASSETS: inlineAssets }, ctx);",
    "  },",
    "};",
    "",
  ].join("\n");
}

function collectPublicFiles(dir, base = dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) {
      out.push(...collectPublicFiles(full, base));
      continue;
    }
    const bytes = readFileSync(full);
    const body = bytes.toString("utf8");
    const path = "/" + relative(base, full).split(sep).join("/");
    if (Buffer.from(body, "utf8").compare(bytes) !== 0) {
      throw new Error(`${path} is not UTF-8 text; the inline build only supports text assets (use the assets upload API instead)`);
    }
    const type = CONTENT_TYPES[extname(name).toLowerCase()];
    if (!type) throw new Error(`${path}: unsupported extension (add it to CONTENT_TYPES)`);
    out.push({ path, type, body });
  }
  return out.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

const sha256 = (buf) => createHash("sha256").update(buf).digest("hex");

function main() {
  if (!process.argv.includes("--skip-bundle")) {
    const wrangler = join(root, "node_modules", "wrangler", "bin", "wrangler.js");
    const res = spawnSync(process.execPath, [wrangler, "deploy", "--dry-run", "--outdir", distDir], { cwd: root, stdio: "inherit" });
    if (res.status !== 0) process.exit(res.status ?? 1);
  }
  const files = collectPublicFiles(publicDir);
  const entry = renderInlineEntry(files);
  mkdirSync(outDir, { recursive: true });
  copyFileSync(join(distDir, "index.js"), join(outDir, "worker.js"));
  writeFileSync(join(outDir, "index.js"), entry);
  console.log(`\ninline build: ${files.length} assets from public/ (${files.map((f) => f.path).join(", ")})`);
  for (const name of ["index.js", "worker.js"]) {
    const buf = readFileSync(join(outDir, name));
    console.log(`${sha256(buf)}  ${String(buf.length).padStart(7)}  dist/inline/${name}`);
  }
}

main();
