// Deterministic synthetic fills for the `demo` ledger. Same seed + anchor => same events.

export const DEFAULT_DEMO_SEED = 42;

const UNIVERSE = [
  { symbol: "AAPL", price: 232.5, lot: 1, weight: 3 },
  { symbol: "MSFT", price: 512.1, lot: 1, weight: 3 },
  { symbol: "NVDA", price: 187.2, lot: 1, weight: 3 },
  { symbol: "SPY", price: 668.4, lot: 10, weight: 2 },
  { symbol: "QQQ", price: 601.2, lot: 10, weight: 2 },
  { symbol: "AMZN", price: 221.9, lot: 1, weight: 2 },
  { symbol: "GOOGL", price: 246.3, lot: 1, weight: 2 },
  { symbol: "TSLA", price: 431.7, lot: 1, weight: 1 },
];
const VENUES = ["NASDAQ", "NYSE", "ARCA", "IEX", "EDGX"];
const TRADING_DAYS = 20;

function mulberry32(seed) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function gaussian(rng) {
  // Box–Muller
  const u = Math.max(rng(), 1e-12);
  const v = rng();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

function pickWeighted(rng, items) {
  const total = items.reduce((s, it) => s + it.weight, 0);
  let r = rng() * total;
  for (const it of items) {
    r -= it.weight;
    if (r <= 0) return it;
  }
  return items[items.length - 1];
}

/** Last `n` weekdays ending at `anchor` (YYYY-MM-DD, UTC), oldest first. */
function tradingDays(anchor, n) {
  const days = [];
  const d = new Date(`${anchor}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) throw new Error(`invalid --anchor "${anchor}" (expected YYYY-MM-DD)`);
  while (days.length < n) {
    const dow = d.getUTCDay();
    if (dow !== 0 && dow !== 6) days.unshift(d.toISOString().slice(0, 10));
    d.setUTCDate(d.getUTCDate() - 1);
  }
  return days;
}

const pad = (n, w) => String(n).padStart(w, "0");
const round = (x, dp) => Math.round(x * 10 ** dp) / 10 ** dp;

export function generateDemoEvents({ count = 300, seed = DEFAULT_DEMO_SEED, anchor } = {}) {
  const rng = mulberry32(seed);
  const anchorDate = anchor ?? new Date().toISOString().slice(0, 10);
  const days = tradingDays(anchorDate, TRADING_DAYS);
  const prices = Object.fromEntries(UNIVERSE.map((u) => [u.symbol, u.price]));
  const events = [];
  let fillIndex = 0;
  let orderIndex = 0;

  events.push({
    id: `demo-${seed}-genesis`,
    ts: `${days[0]}T13:00:00Z`,
    type: "note",
    meta: {
      text: `Synthetic demo ledger generated by open-ledger-publish demo (seed ${seed}). Not real trades.`,
      universe: UNIVERSE.map((u) => u.symbol),
    },
  });

  for (let dayIdx = 0; dayIdx < days.length; dayIdx++) {
    const date = days[dayIdx];
    // Spread `count` fills over the days with mild variation; the last day gets the remainder.
    const remaining = count - fillIndex;
    const daysLeft = days.length - dayIdx;
    const target = dayIdx === days.length - 1 ? remaining : Math.max(1, Math.round((remaining / daysLeft) * (0.6 + rng() * 0.8)));
    const todays = Math.min(remaining, target);

    // Open: drift each symbol overnight.
    for (const u of UNIVERSE) prices[u.symbol] *= 1 + gaussian(rng) * 0.008;

    const times = Array.from({ length: todays }, () => 13.5 * 3600 + Math.floor(rng() * 6.5 * 3600)).sort((a, b) => a - b);
    for (const secOfDay of times) {
      const u = pickWeighted(rng, UNIVERSE);
      prices[u.symbol] *= 1 + gaussian(rng) * 0.0015;
      const px = round(prices[u.symbol], 2);
      const side = rng() < 0.53 ? "buy" : "sell";
      const qty = u.lot * (1 + Math.floor(rng() * 20));
      const hh = pad(Math.floor(secOfDay / 3600), 2);
      const mm = pad(Math.floor((secOfDay % 3600) / 60), 2);
      const ss = pad(secOfDay % 60, 2);
      fillIndex += 1;
      // A bracket parent order can produce two fills; reuse the order id ~20% of the time.
      if (fillIndex === 1 || rng() > 0.2) orderIndex += 1;
      const orderId = `ord-${pad(orderIndex, 5)}`;
      events.push({
        id: `demo-${seed}-fill-${pad(fillIndex, 5)}`,
        ts: `${date}T${hh}:${mm}:${ss}Z`,
        type: "fill",
        symbol: u.symbol,
        side,
        qty,
        price: px,
        orderId,
        broker: "alpaca-paper",
        meta: {
          venue: VENUES[Math.floor(rng() * VENUES.length)],
          liquidity: rng() < 0.6 ? "taker" : "maker",
          clientOrderId: `bracket-${pad(orderIndex, 5)}-${side === "buy" ? "entry" : "exit"}`,
          fee: round(qty * 0.0035, 4),
        },
      });
    }

    events.push({
      id: `demo-${seed}-eod-${date}`,
      ts: `${date}T20:05:00Z`,
      type: "note",
      meta: { text: `EOD reconcile ok: ${todays} fills matched broker activity`, date, fills: todays },
    });
    if (fillIndex >= count) break;
  }
  return events;
}

/** Writes demo fills into a local SQLite file so `tail` can be exercised end-to-end. */
export async function writeDemoSqlite(path, events) {
  const { DatabaseSync } = await import("node:sqlite");
  const db = new DatabaseSync(path);
  try {
    db.exec(`CREATE TABLE IF NOT EXISTS fills (
      fill_id TEXT PRIMARY KEY,
      filled_at TEXT NOT NULL,
      symbol TEXT NOT NULL,
      side TEXT NOT NULL,
      qty REAL NOT NULL,
      price REAL NOT NULL,
      order_id TEXT,
      venue TEXT,
      fee REAL
    )`);
    const insert = db.prepare(
      `INSERT OR IGNORE INTO fills (fill_id, filled_at, symbol, side, qty, price, order_id, venue, fee)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    );
    let written = 0;
    db.exec("BEGIN");
    for (const e of events) {
      if (e.type !== "fill") continue;
      const r = insert.run(e.id, e.ts, e.symbol, e.side, e.qty, e.price, e.orderId, e.meta.venue, e.meta.fee);
      written += Number(r.changes);
    }
    db.exec("COMMIT");
    return written;
  } finally {
    db.close();
  }
}
