/**
 * Deterministic demo ledger: ~200 fake fills (plus a few orders/cancels/notes) for
 * AAPL/MSFT/SPY/NVDA between 2026-09-01 and 2026-10-09, produced by a seeded PRNG so every
 * isolate — and every test run — sees byte-identical events and hashes.
 *
 * Position sequences are generated by a per-symbol state machine (open long, add, partial
 * close, flip, short → cover) so FIFO lot matching is non-trivial. Every fill carries a
 * bracket-order label in `meta` to look like the real Alpaca execution ledger.
 */
import { GENESIS_HASH, hashEvent } from "../ledger/hash";
import type { ChainedEvent, LedgerEvent } from "../ledger/types";

export const DEMO_LEDGER_ID = "demo";
export const DEMO_SEED = 20260901;
export const DEMO_SYMBOLS = ["AAPL", "MSFT", "SPY", "NVDA"] as const;
export const DEMO_START = "2026-09-01";
export const DEMO_END = "2026-10-09";
export const DEMO_BROKER = "alpaca-paper";

/** US market holidays inside the demo window. */
const HOLIDAYS = new Set(["2026-09-07"]);

const START_PRICES: Record<(typeof DEMO_SYMBOLS)[number], number> = {
  AAPL: 232.4,
  MSFT: 514.9,
  SPY: 648.2,
  NVDA: 178.6,
};

/** mulberry32: tiny, fast, good enough for fixtures. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export function tradingDays(from: string, to: string): string[] {
  const days: string[] = [];
  const cursor = new Date(`${from}T00:00:00Z`);
  const end = new Date(`${to}T00:00:00Z`);
  while (cursor.getTime() <= end.getTime()) {
    const dow = cursor.getUTCDay();
    const iso = cursor.toISOString().slice(0, 10);
    if (dow !== 0 && dow !== 6 && !HOLIDAYS.has(iso)) days.push(iso);
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  return days;
}

interface SymbolState {
  price: number;
  position: number;
  /** Entry price of the open bracket, used to label exits take_profit / stop_loss. */
  entryPrice: number | null;
  orderSeq: number;
}

type Draft = Omit<LedgerEvent, "id">;

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

export function generateDemoEvents(seed: number = DEMO_SEED): LedgerEvent[] {
  const rand = mulberry32(seed);
  const pick = <T>(items: readonly T[]): T => items[Math.floor(rand() * items.length)]!;
  const int = (min: number, max: number) => min + Math.floor(rand() * (max - min + 1));

  const states = new Map<string, SymbolState>();
  for (const symbol of DEMO_SYMBOLS) {
    states.set(symbol, { price: START_PRICES[symbol], position: 0, entryPrice: null, orderSeq: 0 });
  }

  const drafts: Draft[] = [];
  let orderCounter = 0;
  const nextOrderId = () => `ord-${String(++orderCounter).padStart(6, "0")}`;

  const days = tradingDays(DEMO_START, DEMO_END);
  for (const [dayIndex, day] of days.entries()) {
    // Regular session 09:30–16:00 ET = 13:30–20:00 UTC (EDT).
    const open = Date.parse(`${day}T13:30:00Z`);
    const minutes = new Set<number>();
    const fillsToday = int(5, 9);
    while (minutes.size < fillsToday + 1) minutes.add(int(1, 389));
    const slots = [...minutes].sort((a, b) => a - b);

    // Daily drift per symbol.
    for (const state of states.values()) {
      state.price = round2(state.price * (1 + (rand() - 0.5) * 0.024));
    }

    drafts.push({
      ts: new Date(open).toISOString(),
      type: "note",
      broker: DEMO_BROKER,
      meta: { kind: "session_open", session: day, note: `paper session ${dayIndex + 1}/${days.length}` },
    });

    for (const [i, minute] of slots.entries()) {
      const ts = new Date(open + minute * 60_000 + int(0, 59) * 1_000).toISOString();
      const symbol = pick(DEMO_SYMBOLS);
      const state = states.get(symbol)!;
      const px = round2(state.price * (1 + (rand() - 0.5) * 0.008));

      // Occasionally emit an unfilled bracket (order + cancel) instead of a fill.
      if (i === slots.length - 1 && dayIndex % 3 === 1) {
        const orderId = nextOrderId();
        const side = state.position >= 0 ? "buy" : "sell";
        const qty = int(5, 25);
        drafts.push({ ts, type: "order", symbol, side, qty, price: round2(px * (side === "buy" ? 0.995 : 1.005)), orderId, broker: DEMO_BROKER, meta: { strategy: "bracket", leg: "entry", tif: "day" } });
        drafts.push({ ts: new Date(Date.parse(ts) + 45_000).toISOString(), type: "cancel", symbol, orderId, broker: DEMO_BROKER, meta: { reason: "unfilled_at_close" } });
        continue;
      }
      if (i === slots.length - 1) continue; // last slot reserved for order/cancel days

      let side: "buy" | "sell";
      let qty: number;
      let leg: "entry" | "scale_in" | "take_profit" | "stop_loss" | "flip" | "cover";
      const r = rand();
      if (state.position === 0) {
        side = r < 0.72 ? "buy" : "sell";
        qty = side === "buy" ? int(10, 50) : int(10, 30);
        leg = "entry";
        state.entryPrice = px;
      } else if (state.position > 0) {
        if (r < 0.4) {
          side = "buy";
          qty = int(5, 25);
          leg = "scale_in";
        } else if (r < 0.9) {
          side = "sell";
          qty = r < 0.65 ? int(1, state.position) : state.position;
          leg = state.entryPrice !== null && px >= state.entryPrice ? "take_profit" : "stop_loss";
        } else {
          side = "sell";
          qty = state.position + int(5, 20);
          leg = "flip";
          state.entryPrice = px;
        }
      } else {
        const shortQty = -state.position;
        if (r < 0.6) {
          side = "buy";
          qty = r < 0.35 ? int(1, shortQty) : shortQty;
          leg = "cover";
        } else if (r < 0.9) {
          side = "sell";
          qty = int(5, 20);
          leg = "scale_in";
        } else {
          side = "buy";
          qty = shortQty + int(5, 20);
          leg = "flip";
          state.entryPrice = px;
        }
      }
      state.position += side === "buy" ? qty : -qty;
      if (state.position === 0) state.entryPrice = null;
      drafts.push({
        ts,
        type: "fill",
        symbol,
        side,
        qty,
        price: px,
        orderId: nextOrderId(),
        broker: DEMO_BROKER,
        meta: { strategy: "bracket", leg, session: day },
      });
    }
  }

  drafts.sort((a, b) => a.ts.localeCompare(b.ts));
  return drafts.map((draft, index) => ({ id: `evt-${String(index + 1).padStart(6, "0")}`, ...draft }));
}

/** Chain bare events in order: seq starts at 1, prevHash of the first event is the genesis hash. */
export async function chainEvents(events: readonly LedgerEvent[], firstSeq = 1): Promise<ChainedEvent[]> {
  const chained: ChainedEvent[] = [];
  let prevHash = GENESIS_HASH;
  for (const [index, event] of events.entries()) {
    const hash = await hashEvent(prevHash, event);
    chained.push({ ...event, seq: firstSeq + index, prevHash, hash });
    prevHash = hash;
  }
  return chained;
}

let demoChainPromise: Promise<ChainedEvent[]> | undefined;

/** Built lazily once per isolate (hashing ~250 events costs a few ms of CPU). */
export function getDemoChain(): Promise<ChainedEvent[]> {
  demoChainPromise ??= chainEvents(generateDemoEvents());
  return demoChainPromise;
}
