/**
 * Worker environment.
 *
 * `Cloudflare.Env` is generated by `wrangler types` from wrangler.jsonc (and from
 * `.dev.vars` when present). Secrets are intersected in as optional so the type is
 * stable whether or not a local `.dev.vars` exists.
 */
export type LedgerEnv = Cloudflare.Env & {
  /** Bearer token required on /mcp and /sse. Set with `wrangler secret put MCP_API_KEY`. */
  MCP_API_KEY?: string;
  /** open-ledger base URL. Unset → built-in deterministic demo ledger. */
  LEDGER_BASE_URL?: string;
  /** Alpaca Market Data v2 credentials (optional). */
  ALPACA_KEY_ID?: string;
  ALPACA_SECRET_KEY?: string;
};

export const SERVER_NAME = "ledger-mcp";
export const SERVER_VERSION = "0.1.0";

/** Hard caps chosen for the Workers Free plan (10 ms CPU per invocation). */
export const LIMITS = {
  /** Max events returned by one `ledger_events` call (also the upstream page size cap). */
  eventsPerCall: 1000,
  /** Max events folded into one `ledger_pnl` / local `ledger_summary` computation. */
  pnlEvents: 5000,
  /** Max (to - from + 1) for one `ledger_verify` call. */
  verifyRange: 2000,
  /** Max bars per `market_bars` call. */
  bars: 1000,
} as const;

export function defaultLedgerId(env: Pick<LedgerEnv, "LEDGER_DEFAULT_ID">): string {
  return env.LEDGER_DEFAULT_ID || "demo";
}
